### ISSUE TITLE
The authorization of this user failed with error 5

### ISSUE THREAD

**Issue by ytymchnk** [devops-collective-inc/secrets-of-powershell-remoting#1]
Thanks for the great article, Don.

While implementing this, when I finally go to create a new powershell session using a certificate thumbprint, I get an “access denied” error message.

On the host that I am trying to remote to, the WinRM event viewer Operational log shows an Informational Event ID 192.  Test of the event is “The authorization of this user failed with error 5”.

I’ve mapped the client certificate on the server to the local Administrator account (Builtin)  The firewalls on both machines are not active.  Both machines are in the same domain and are on the same subnet. Both run Windows Server 2012 R2.

Have you ever run across this before?

Thanks,

Chris

**Comment by jyothi-or** [comment]
Hi @ytymchnk were you able to fix this issue ? I am facing a similar issue.
